# Generated by Django 6.0 on 2025-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso (+)'), ('EGRESO', 'Egreso (-)')], max_length=10)),
                ('categoria', models.CharField(choices=[('ALIMENTOS', 'Compra de Alimentos'), ('DONACION', 'Donación Recibida'), ('SERVICIOS', 'Servicios Básicos (Luz/Agua/Gas)'), ('SUELDOS', 'Sueldos/Limpieza'), ('OTROS', 'Otros')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=255, verbose_name='Detalle del gasto/ingreso')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Contabilidad (Ingresos y Egresos)',
            },
        ),
    ]
