# Generated by Django 6.0 on 2025-12-20 14:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(default='Ecuatoriana', max_length=50)),
                ('direccion', models.TextField(verbose_name='Dirección Domiciliaria')),
                ('contacto', models.CharField(max_length=50, verbose_name='Teléfono de Contacto')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cuota Mensual')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Beneficiario',
                'verbose_name_plural': 'Beneficiarios',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula/DNI')),
                ('nacionalidad', models.CharField(default='Ecuatoriana', max_length=50)),
                ('empleo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación/Empleo')),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ingresos Mensuales')),
                ('convivencia', models.CharField(max_length=100, verbose_name='Con quién vive el niño')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.CharField(blank=True, max_length=100, verbose_name='Institución Educativa')),
                ('grado', models.CharField(blank=True, max_length=50, verbose_name='Grado/Curso')),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beneficiarios.beneficiary', verbose_name='Beneficiario')),
            ],
            options={
                'verbose_name': 'Inscripción Escolar',
                'verbose_name_plural': 'Inscripciones Escolares',
            },
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='representative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representados', to='beneficiarios.representative', verbose_name='Representante'),
        ),
    ]
